name: Flutter CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - '!\d+\.\d+\.\d+'

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: cirrusci/flutter:stable
      options: -u root

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter test
